import { z } from "zod";

const nonNegativeInteger = z.number().int().nonnegative();
const selection = z.union([z.array(z.string().min(1)).min(1), z.string().min(1).transform((value) => [value])]);
const qp = z.object({ questionId: z.string(), status: z.enum(["new", "learning", "mastered"]), totalAttempts: nonNegativeInteger, correctCount: nonNegativeInteger, incorrectCount: nonNegativeInteger, dontKnowCount: nonNegativeInteger, correctStreak: nonNegativeInteger, lastSelectedOptionIds: selection.nullable().optional(), lastSelectedOptionId: z.string().nullable().optional(), lastResult: z.enum(["correct", "incorrect", "dont-know"]).nullable(), firstSeenAt: z.string().nullable(), lastSeenAt: z.string().nullable(), masteredAt: z.string().nullable() }).transform(({ lastSelectedOptionId, ...record }) => ({ ...record, lastSelectedOptionIds: record.lastSelectedOptionIds ?? (lastSelectedOptionId ? [lastSelectedOptionId] : null) }));
const item = z.object({ instanceId: z.string().min(1), questionId: z.string().min(1), reason: z.enum(["initial", "retry"]), answered: z.boolean() });
const attempt = z.object({ id: z.string().min(1), queueInstanceId: z.string().min(1), questionId: z.string().min(1), selectedOptionIds: selection.nullable().optional(), selectedOptionId: z.string().nullable().optional(), result: z.enum(["correct", "incorrect", "dont-know"]), answeredAt: z.string() }).transform(({ selectedOptionId, ...record }) => ({ ...record, selectedOptionIds: record.selectedOptionIds ?? (selectedOptionId ? [selectedOptionId] : null) }));

export const progressSchema = z.object({ schemaVersion: z.literal(1), subjectId: z.string().min(1), subjectContentVersion: z.number().int().positive(), questionProgress: z.record(z.string(), qp), activeSession: z.object({ schemaVersion: z.literal(1), sessionId: z.string().min(1), subjectId: z.string().min(1), subjectContentVersion: z.number().int().positive(), createdAt: z.string(), updatedAt: z.string(), completedAt: z.string().nullable(), queue: z.array(item).min(1), currentIndex: nonNegativeInteger, frontierIndex: nonNegativeInteger, attempts: z.array(attempt), settings: z.object({ shuffleQuestions: z.boolean(), shuffleOptions: z.boolean(), masteryStreak: z.number().int().positive(), retryGap: nonNegativeInteger }) }).nullable(), completedSessionCount: nonNegativeInteger, lifetimeAttempts: nonNegativeInteger, lastStudiedAt: z.string().nullable() });
